#!/usr/bin/perl

while (1) {
      my $b;
      if (sysread(STDIN, $b, 2) != 2) {
	  exit;
      }

      # the raw data is low byte first, of course. Grr.
      my ($a) = unpack('v', $b);

      # Drop 4 bits off the top.
      $a >>= 4;

      # Add the D/A header (%0011xxxx).
      $a |= 0x3000;

      # Print out a new value in big-endian order.
      my $c = pack('n', $a);
      syswrite(STDOUT, $c, 2);
}

